name: weixin

on:
  workflow_dispatch:
  schedule: 
    # 每天北京时间早上7点运行（UTC时间23点）
    - cron: '0 23 * * *'

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v4  # 推荐使用 v4
        with:
          python-version: '3.9'        # 使用主版本号自动选择可用小版本

      - name: Set timezone
        run: |
          sudo cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

      - name: install pip packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: weixin
        run: |
          python main.py
